package com.jojoalex.ticket.model.entities;
// Generated 23-Apr-2018 2:15:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="Client"
    ,catalog="tickets"
    , uniqueConstraints = {@UniqueConstraint(columnNames="phone"), @UniqueConstraint(columnNames="email")} 
)
public class Client  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String fullname;
     private String phone;
     private String email;
     private String password;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Client() {
    }

	
    public Client(User user, String fullname, String phone, String email, String password) {
        this.user = user;
        this.fullname = fullname;
        this.phone = phone;
        this.email = email;
        this.password = password;
    }
    public Client(User user, String fullname, String phone, String email, String password, Set<Ticket> tickets) {
       this.user = user;
       this.fullname = fullname;
       this.phone = phone;
       this.email = email;
       this.password = password;
       this.tickets = tickets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="fullname", nullable=false)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=11)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", unique=true, nullable=false, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


