package com.jojoalex.ticket.model.entities;
// Generated 23-Apr-2018 2:15:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="Ticket"
    ,catalog="tickets"
)
public class Ticket  implements java.io.Serializable {


     private Integer id;
     private Client client;
     private User user;
     private String title;
     private String content;
     private Date createdAt;
     private Date closedAt;
     private String priority;
     private Set<TicketUpdate> ticketUpdates = new HashSet<TicketUpdate>(0);

    public Ticket() {
    }

	
    public Ticket(Client client, String title, String content, Date createdAt, String priority) {
        this.client = client;
        this.title = title;
        this.content = content;
        this.createdAt = createdAt;
        this.priority = priority;
    }
    public Ticket(Client client, User user, String title, String content, Date createdAt, Date closedAt, String priority, Set<TicketUpdate> ticketUpdates) {
       this.client = client;
       this.user = user;
       this.title = title;
       this.content = content;
       this.createdAt = createdAt;
       this.closedAt = closedAt;
       this.priority = priority;
       this.ticketUpdates = ticketUpdates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="opened_by", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="closed_by")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="closed_at", length=19)
    public Date getClosedAt() {
        return this.closedAt;
    }
    
    public void setClosedAt(Date closedAt) {
        this.closedAt = closedAt;
    }

    
    @Column(name="priority", nullable=false)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<TicketUpdate> getTicketUpdates() {
        return this.ticketUpdates;
    }
    
    public void setTicketUpdates(Set<TicketUpdate> ticketUpdates) {
        this.ticketUpdates = ticketUpdates;
    }




}


